### ISSUE TITLE
pod 'MOLPaySDK' doesn't install the latest version

### ISSUE THREAD

**Issue by pankkor** [MOLPay/Mobile_SDK-iOS_Cocoapods#1]
```pod 'MOLPaySDK'``` installs MOLPay version 4.6.0.7 instead of the latest 4.6.0.8
You can check https://cocoapods.org/?q=Molpay as well.
Probably due to your version not conforming to [semver](http://semver.org/)

**Comment by clewlb** [comment]
@pankkor ,
Thanks for your feedback, for some reason Cocoapods pod lint didn't catch any error on the version string and the version number didn't get updated accordingly after the podspec get submitted. Please set below in your pod file instead,

pod 'MOLPaySDK', :git => 'https://github.com/MOLPay/Mobile_SDK-
iOS_Cocoapods.git', :tag => '4.0.6.8'

**Comment by pankkor** [comment]
Do you believe [semver](http://semver.org/) versioning can help?

**Comment by clewlb** [comment]
@pankkor,
Yes we believe so. And we will fix that in the coming updates. Thanks for your suggestion.

**Comment by clewlb** [comment]
@pankkor,
Some interesting findings, Semver may not be irrelevant to this issue according to this conversation, https://github.com/CocoaPods/guides.cocoapods.org/issues/52. Anyway, we will definitely look into this issue on our future updates.
