### ISSUE TITLE
"cash" or "Cash-711"?

### ISSUE THREAD

**Issue by pankkor** [MOLPay/Mobile_SDK-iOS_Cocoapods#3]
In previous versions ```-resultRequestSuccessWithPaymentDetails:``` and ```-resultRequestFailedWithErrorDescription:``` returned ```{"channel" : "cash"}``` and now it returns ```{"channel" : "Cash-711"}```. Documentation still uses ```"cash"``` and for ```MOLPayLib``` initialization we still use ```{mp_channel : "cash"}```. Which one is an expected return parameter from ```resultRequestSuccessWithPaymentDetails:``` then?

**Comment by clewlb** [comment]
@pankkor, "Cash-711" is the channel name of the channel id "cash", you may need to implement your own mechanism to map the name to the id if you want to use the channel name in your application.

**Comment by clewlb** [comment]
@pankkor, btw, if you will, please try out our new series of mobile sdk, https://github.com/MOLPay/molpay-mobile-xdk-cocoapods, this will eventually replace the previous versions.

**Comment by pankkor** [comment]
@clewlb ok, got it. Thank you for your response.
